#!/usr/bin/env node

/**
 * term.css theme generator
 * Usage: npx termcss --hue 165 --name ocean [--chroma 0.15] [--out <path>]
 */

import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { parseArgs } from "util";
import { oklchToLuminance, contrastRatio } from "./color.js";

const { values } = parseArgs({
  options: {
    hue: { type: "string" },
    name: { type: "string" },
    chroma: { type: "string", default: "0.15" },
    out: { type: "string" },
  },
});

if (!values.hue || !values.name) {
  console.error("Usage: npx termcss --hue <0-360> --name <name> [--chroma <0-0.4>] [--out <path>]");
  process.exit(1);
}

const hue = parseFloat(values.hue);
const chroma = parseFloat(values.chroma);
const name = values.name;

if (Number.isNaN(hue) || hue < 0 || hue > 360) {
  console.error("ERROR: --hue must be a number between 0 and 360");
  process.exit(1);
}

if (Number.isNaN(chroma) || chroma < 0 || chroma > 0.4) {
  console.error("ERROR: --chroma must be a number between 0 and 0.4");
  process.exit(1);
}

if (!/^[a-z0-9-]+$/.test(name)) {
  console.error("ERROR: --name must contain only lowercase letters, numbers, and hyphens");
  process.exit(1);
}

// Fixed lightness values that guarantee WCAG AA contrast
const dark = {
  bg:      { L: 0.15, C: 0.02 },
  fg:      { L: 0.85, C: 0.02 },
  muted:   { L: 0.58, C: 0.02 },
  accent:  { L: 0.75, C: chroma },
  accent2: { L: 0.65, C: chroma },
  surface: { L: 0.20, C: 0.02 },
  border:  { L: 0.30, C: 0.02 },
};

const light = {
  bg:      { L: 0.97, C: 0.01 },
  fg:      { L: 0.20, C: 0.02 },
  muted:   { L: 0.45, C: 0.02 },
  accent:  { L: 0.45, C: chroma },
  accent2: { L: 0.50, C: chroma * 0.8 },
  surface: { L: 0.93, C: 0.01 },
  border:  { L: 0.80, C: 0.01 },
};

// Syntax colors - rotate hue for variety
const syntaxHues = {
  keyword:     (hue + 145) % 360,
  string:      (hue + 340) % 360,
  comment:     hue,
  function:    (hue + 275) % 360,
  number:      (hue + 245) % 360,
  operator:    (hue + 35) % 360,
  type:        (hue + 55) % 360,
};

function oklch(L, C, H) {
  return `oklch(${L.toFixed(2)} ${C.toFixed(2)} ${H.toFixed(0)})`;
}


function generateLightDark(lightVars, darkVars, modeHue, lightSyntaxL, darkSyntaxL) {
  const lines = [];
  for (const key of Object.keys(lightVars)) {
    const l = lightVars[key];
    const d = darkVars[key];
    lines.push(`  --t-${key}: light-dark(${oklch(l.L, l.C, modeHue)}, ${oklch(d.L, d.C, modeHue)});`);
  }
  lines.push(`  --t-red: light-dark(oklch(0.55 0.20 25), oklch(0.65 0.20 25));`);
  lines.push(`  --t-yellow: light-dark(oklch(0.55 0.16 85), oklch(0.78 0.16 85));`);
  lines.push(`  --t-green: light-dark(oklch(0.50 0.17 145), oklch(0.72 0.19 145));`);
  lines.push("");
  for (const [token, tokenHue] of Object.entries(syntaxHues)) {
    lines.push(`  --t-syntax-${token}: light-dark(${oklch(lightSyntaxL, chroma, tokenHue)}, ${oklch(darkSyntaxL, chroma, tokenHue)});`);
  }
  lines.push(`  --t-syntax-punctuation: var(--t-muted);`);
  return lines.join("\n");
}

// Generate CSS
const css = `/* ${name} - generated by term.css theme generator */
/* Hue: ${hue}, Chroma: ${chroma} */

:root {
  color-scheme: light dark;

${generateLightDark(light, dark, hue, 0.45, 0.75)}
}

:root[data-theme="light"] {
  color-scheme: light;
}

:root[data-theme="dark"] {
  color-scheme: dark;
}
`;

const outPath = values.out
  ? resolve(values.out)
  : resolve(process.cwd(), `${name}.css`);

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css);

// Validate contrast ratios using proper OKLCH → luminance conversion
function lum(vars, key) {
  return oklchToLuminance(vars[key].L, vars[key].C !== undefined ? vars[key].C : chroma, hue);
}
const darkBgY = lum(dark, "bg");
const lightBgY = lum(light, "bg");

// Semantic colors (fixed hue/chroma)
const semRed   = { lightY: oklchToLuminance(0.55, 0.20, 25), darkY: oklchToLuminance(0.65, 0.20, 25) };
const semYellow = { lightY: oklchToLuminance(0.55, 0.16, 85), darkY: oklchToLuminance(0.78, 0.16, 85) };
const semGreen = { lightY: oklchToLuminance(0.50, 0.17, 145), darkY: oklchToLuminance(0.72, 0.19, 145) };

const checks = [
  { label: "Dark  fg/bg",      ratio: contrastRatio(lum(dark, "fg"), darkBgY),       min: 4.5 },
  { label: "Dark  muted/bg",   ratio: contrastRatio(lum(dark, "muted"), darkBgY),    min: 4.5 },
  { label: "Dark  accent/bg",  ratio: contrastRatio(lum(dark, "accent"), darkBgY),   min: 4.5 },
  { label: "Light fg/bg",      ratio: contrastRatio(lum(light, "fg"), lightBgY),     min: 4.5 },
  { label: "Light muted/bg",   ratio: contrastRatio(lum(light, "muted"), lightBgY),  min: 4.5 },
  { label: "Light accent/bg",  ratio: contrastRatio(lum(light, "accent"), lightBgY), min: 4.5 },
  { label: "Light red/bg",     ratio: contrastRatio(semRed.lightY, lightBgY),        min: 4.5 },
  { label: "Dark  red/bg",     ratio: contrastRatio(semRed.darkY, darkBgY),          min: 4.5 },
  { label: "Light yellow/bg",  ratio: contrastRatio(semYellow.lightY, lightBgY),     min: 4.5 },
  { label: "Dark  yellow/bg",  ratio: contrastRatio(semYellow.darkY, darkBgY),       min: 4.5 },
  { label: "Light green/bg",   ratio: contrastRatio(semGreen.lightY, lightBgY),      min: 4.5 },
  { label: "Dark  green/bg",   ratio: contrastRatio(semGreen.darkY, darkBgY),        min: 4.5 },
];

console.log(`\nTheme "${name}" generated at: ${outPath}\n`);
console.log("Contrast ratios:");
let failed = false;
for (const { label, ratio, min } of checks) {
  const pass = ratio >= min;
  const icon = pass ? "✓" : "✗";
  console.log(`  ${icon} ${label}: ${ratio.toFixed(1)}:1 (need ${min}:1)`);
  if (!pass) failed = true;
}

if (failed) {
  console.error("\nFAILED: One or more contrast ratios below WCAG AA threshold.");
  process.exit(1);
} else {
  console.log("\nAll contrast ratios pass WCAG AA.");
}
